Added clones shield bumping

diff --git a/.github/workflows/update-root-npm-shield-weekly.yml b/.github/workflows/update-root-npm-shield-weekly.yml
--- a/.github/workflows/update-root-npm-shield-weekly.yml
+++ b/.github/workflows/update-root-npm-shield-weekly.yml
@@ -1,11 +1,11 @@
-name: Update npm downloads shield in root README
+name: Update npm/clones shields in root README
 
 on:
   schedule:
     - cron: "17 0 * * 0" # every Sunday 12:17a
 
 jobs:
-  update-downloads-shield:
+  update-root-npm-clones-shields:
     runs-on: ubuntu-latest
     
     steps:
@@ -16,7 +16,7 @@ jobs:
           repository: adamlui/minify.js
           path: adamlui/minify.js
       
-      - name: Fetch/sum npm download counts
+      - name: Fetch/sum npm download + git clone counts
         id: get-stats
         run: |
           npm_pkgs=("@adamlui/minify.js" "gulp-minify.js")
@@ -66,25 +66,67 @@ jobs:
             total_downloads=$((total_downloads + pkg_downloads))
           done ; echo -e "\n-----\nTotal monthly npm downloads: $total_downloads\n-----\n"
 
-          # Format total
+          # Fetch/calculate git clone count
+          biweekly_clones=$(curl -sSL \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.REPO_SYNC_PAT }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/adamlui/minify.js/traffic/clones" |
+            sed -n -E '0,/.*"count": ([0-9]+).*/ s//\1/p')
+          total_clones=$((biweekly_clones * 2))
+          echo "Biweekly git clones: $biweekly_clones"
+          echo -e "\n-----\nTotal monthly git clones: $total_clones\n-----\n"
+
+          # Format totals
           formatted_total_downloads=$(format_total "$total_downloads")
           echo "Formatted total monthly npm downloads: $formatted_total_downloads"
+          formatted_total_clones=$(format_total "$total_clones")
+          echo "Formatted total monthly git clones: $formatted_total_clones"
 
           # Expose as output for update step next
           echo "total_downloads=$formatted_total_downloads" >> $GITHUB_OUTPUT
+          echo "total_clones=$formatted_total_clones" >> $GITHUB_OUTPUT
       
       - name: Update README shields
+        id: update-shields
         run: |
           cd ${{ github.workspace }}/adamlui/minify.js
+
           total_downloads="${{ steps.get-stats.outputs.total_downloads }}"
+          total_clones="${{ steps.get-stats.outputs.total_clones }}"
+
+          # Update npm shield
           if [ "$total_downloads" == "0" ] ; then echo "Error getting total npm downloads"
           else
             old_readme=$(<docs/README.md)
-            sed -i -E "s|(badge/Downloads-)[0-9.,km+]+|\1$total_downloads|Ig" docs/README.md ; fi
+            sed -i -E "s|(badge/Downloads-)[0-9.,km+]+|\1$total_downloads|Ig" docs/README.md
             new_readme=$(<docs/README.md)
-            if [ "$old_readme" != "$new_readme" ] ; then echo "npm downloads shield updated to $total_downloads"
-            else echo "npm downloads shield already up-to-date" ; fi
+            if [ "$old_readme" != "$new_readme" ] ; then downloads_updated=true ; fi
+            if [ "$downloads_updated" = true ] ; then echo "npm shield updated to $total_downloads"
+            else echo "npm shield already up-to-date" ; fi
           fi
+
+          # Update git clones shield
+          if [ "$total_clones" == "0" ] ; then echo "Error getting total git clones"
+          else # perform update
+            old_readme=$(<docs/README.md)
+            sed -i -E "s|(badge/[^-]+-)[0-9.,km+]+(/[^?]+\?logo=github)|\1$total_clones\2|gI" docs/README.md
+            new_readme=$(<docs/README.md)
+            if [ "$old_readme" != "$new_readme" ] ; then clones_updated=true ; fi
+            if [ "$clones_updated" = true ] ; then echo "Git clones shields updated to $total_clones"
+            else echo "Git clones shields up-to-date already" ; fi
+          fi
+
+          # Define commit msg for push step next
+          if [ "$downloads_updated" = true ] && [ "$clones_updated" = true ] ; then
+            multi_shield_types_updated=true ; fi
+          commit_msg="Updated "
+          [ "$downloads_updated" = true          ] && commit_msg+="npm"
+          [ "$multi_shield_types_updated" = true ] && commit_msg+="/"
+          [ "$clones_updated" = true             ] && commit_msg+="clones"
+          commit_msg+=" shield counter$([ "$multi_shield_types_updated" = true ] && echo "s")"
+          commit_msg+=" in root README"
+          echo "commit_msg=$commit_msg" >> $GITHUB_OUTPUT # expose as output
 
       - name: Push to adamlui/minify.js
         run: |
@@ -92,5 +134,5 @@ jobs:
           git config --global user.name "kudo-sync-bot"
           git config --global user.email "auto-sync@kudoai.com"
           git add .
-          git commit -n -m "Updated downloads shield counter in root README" || true
+          git commit -n -m "${{ steps.update-shields.outputs.commit_msg }}" || true
           git push
